### ISSUE TITLE
Ability to update registered instance after it has been resolved

### ISSUE THREAD

**Issue by icnocop** [gasparnagy/BoDi#23] opened 2019-05-16 09:02 UTC
I'd like to be able to update a registered instance after it has been resolved.

Currently, when I try to do this, I get the exception:
`ObjectContainerException: "An object has been resolved for this interface already.`

For reference, `AutoFac` has this ability with an `Update` method.

Thank you.

**Comment by gasparnagy** [comment] 2019-05-16 09:28
This is not easy, becasue the instances might have cached to the child containers and the parent container does not have a reference to the children, so we cannot even invalidate it there.
If you tell more about the context, maybe I can suggest an better alternative, but in general when the dependencies need to be changed, I either try to register it to sub-containers and use different sub-containers or register a context/wrapper class with a normal updatable reference.
BoDi is kept simple by design. You can also use SpecFlow with AutoFac using the SpecFlow.AutoFac package.

**Comment by icnocop** [comment] 2019-05-16 10:10
Thank you, @gasparnagy.

I will try to use a wrapper class.

**Comment by gasparnagy** [comment] 2019-05-16 11:48
ok. i close this, please reopen if the wrapper does not solve your problem.

**Closed by gasparnagy** 2019-05-16 11:48 UTC
